# Generated by Django 5.2.14 on 2026-05-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=200, unique=True)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Mixed', 'Mixed')], max_length=10)),
                ('total_rooms', models.PositiveIntegerField()),
                ('address', models.TextField(blank=True, default='')),
                ('contact_number', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'ordering': ['hostel_name'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single', 'Single Occupancy'), ('Double', 'Double Occupancy'), ('Triple', 'Triple Occupancy'), ('Dormitory', 'Dormitory')], max_length=20)),
                ('available_rooms', models.PositiveIntegerField(default=0)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Course for which this room type is allocated (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_rooms', to='courses.course')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'verbose_name': 'Hostel Room',
                'verbose_name_plural': 'Hostel Rooms',
                'ordering': ['hostel', 'room_type'],
            },
        ),
    ]
