# Generated by Django 5.2.14 on 2026-05-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Guest Faculty', 'Guest Faculty')], max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_set', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='courses.department')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['faculty_name'],
            },
        ),
    ]
