# Generated by Django 6.0.4 on 2026-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
